# Generated by Django 4.1.7 on 2023-04-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('anio', models.PositiveIntegerField()),
                ('nroCiclo', models.PositiveIntegerField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
